name: Pull Request Label Management

# This workflow automatically lables PR to ensure that all PR's are correct within the release draft.

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  awaitCheck:
    runs-on: ubuntu-latest
    steps:
      # This step will retry until required check passes
      # and will fail the whole workflow if the check conclusion is not a success
      - name: Wait on wip checks
        uses: lewagon/wait-on-check-action@v0.1-beta.2
        with:
          ref: ${{github.sha}} # can be commit SHA or tag too
          check-name: wip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20 # seconds

  # Automatically labels based on files changed
  labeler:
    name: Pull Labeler
    needs: awaitCheck
    runs-on: ubuntu-latest
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.0-beta
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2.3.1
      # super Labeler
      - name: Super Labeller
        uses: IvanFon/super-labeler-action@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      # Label size based (soon to be merged with super labeler)
      - uses: actions-ecosystem/action-size@v2
        if: ${{env.size_enabled}} == true
        id: size
        with:
          size_xs_label: ${{env.size_xs_label}}
          size_s_label: ${{env.size_s_label}}
          size_m_label: ${{env.size_m_label}}
          size_l_label: ${{env.size_l_label}}
          size_xl_label: ${{env.size_xl_label}}
          size_xxl_label: ${{env.size_xxl_label}}
        continue-on-error: true
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{env.size_enabled}} == true
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.stale_labels }}
        continue-on-error: true
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{env.size_enabled}} == true
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.new_label }}
        continue-on-error: true

      # Sponsor labels
      - uses: JasonEtco/is-sponsor-label-action@v1
        if: github.event.action == 'opened' && ${{env.sponsor_enabled}} == true
        with:
          label: ${{env.sponsor_label}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      # - uses: actions/labeler@v2
      #   if: ${{env.path_enabled}} == true
      #   with:
      #     configuration-path: ${{env.path_config}}
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     continue-on-error: true
      # - uses: TimonVS/pr-labeler-action@v3
      #   if: ${{env.branch_enabled}} == true
      #   with:
      #     configuration-path: ${{env.branch_Config}}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   continue-on-error: true
