name: Pull Request Management

# This workflow automatically lables PR to ensure that all PR's are correct within the release draft.

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  awaitCheck:
    runs-on: ubuntu-latest
    steps:
      # This step will retry until required check passes
      # and will fail the whole workflow if the check conclusion is not a success
      - name: Wait on wip checks
        uses: lewagon/wait-on-check-action@v0.1-beta.2
        with:
          ref: ${{github.sha}} # can be commit SHA or tag too
          check-name: wip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20 # seconds

  # Ensures semantic titles to ensure semantic is achieved when merge is squashed
  conventional:
    name: Conventional PR Title
    needs: awaitCheck
    runs-on: ubuntu-latest
    steps:
      - name: Get Configurations
        uses: Videndum/manage-github-secrets@1.0.0-beta
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check title
        if: ${{env.semantic_enabled}} == true
        uses: aslafy-z/conventional-pr-title-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
